spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/smart_attendance_db
spring.datasource.username=root
spring.datasource.password=@Hanif18

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
